karhoo/karhoo-ios-sdk

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/Request/TripBooking.swift
KarhooSDK/Info.plist
KarhooSDKTests/TestCases/Service/Trips/BookingInteractor/KarhooBookingInteractorSpec.swift

Added optional 'comments' field for trip request. 

MOB-XXXX added comments field

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Service/Auth/RevokeInteractor/KarhooAuthRevokeInteractor.swift

-pod lib lint proof
- pushed cocoapods trunk
- [] Bugfix 

MOB-XXXX [Public cocoapod support] 

---

KarhooSDK/Api/Response/TripInfo.swift
KarhooSDK/Api/Response/TripQuote.swift
KarhooSDKIntegrationTests/JSON/Trip/TripInfo.json
KarhooSDKIntegrationTests/Service/Trip/BookTripMethodSpec.swift

[MOB-390](https://karhoo.atlassian.net/browse/MOB-390)

[MOB-390] Deprecate Quotes

---

KarhooSDK/Service/Analytics/AnalyticsConstants.swift
KarhooSDK/Service/Analytics/AnalyticsPayloadBuilder.swift

[MOB-2702](https://karhoo.atlassian.net/browse/MOB-2702)
Adds a field to default analytics payload identifying if the current user is a guest or not.

MOB-2702 [Guest mode analytics]

---

KarhooSDK.podspec

[MOB-XXXX]1.1.2 release

---

KarhooSDK.podspec
KarhooSDK/Service/Analytics/AnalyticsPayloadBuilder.swift

[MOB-2702](https://karhoo.atlassian.net/browse/MOB-2702)
- Misplaced guard statement meant guest_mode event was not being added to analytics payload  

[MOB-2702-patch] Analytics fix

---

KarhooSDK/Network/APIEndpoint.swift
KarhooSDK/Network/Common/Error/KarhooErrorType.swift

[MOB-2874](https://karhoo.atlassian.net/browse/MOB-2874)
Updated nonce url and added new errors (Noted error "P0001" missing)

[MOB-2874] Migrate nonce URL

---

KarhooSDK/Network/APIEndpoint.swift
KarhooSDK/Service/Availability/AvailabilityService.swift

[MOB-2862](https://karhoo.atlassian.net/browse/MOB-2862)
deprecate availability

MOB-2862 deprecate availability

---

Cartfile
Cartfile.resolved
Client/AppDelegate.swift
KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK.xcodeproj/xcshareddata/xcschemes/KarhooSDKTests.xcscheme
KarhooSDK/Api/Request/QuoteListIdRequestPayload.swift
KarhooSDK/Api/Request/QuoteRequest.swift
KarhooSDK/Api/Request/QuoteRequestPayload .swift
KarhooSDK/Api/Request/QuoteRequestPoint.swift
KarhooSDK/Api/Response/Availability.swift
KarhooSDK/Api/Response/QuoteList.swift
KarhooSDK/Api/Response/VehicleAvailability.swift
KarhooSDK/Network/APIEndpoint.swift
KarhooSDK/Service/Availability/AvailabilityService.swift
KarhooSDK/Service/Quote/CategoryQuoteMapper.swift
KarhooSDK/Service/Quote/Interactor/KarhooQuoteInteractor.swift
KarhooSDK/Service/Quote/Interactor/KarhooQuoteInteractorV2.swift
KarhooSDKIntegrationTests/Service/Quote/QuoteSearchMethodSpec.swift
KarhooSDKTests/TestCases/Service/Quote/CategoryQuoteMapperSpec.swift
KarhooSDKTests/TestCases/Service/Quote/Interactor/KarhooQuoteInteractorSpecV2.swift

[MOB-2853](https://karhoo.atlassian.net/browse/MOB-2853)
- [] All work relating to the ticket is complete (Code complete/Acceptance Criteria met)

MOB-2853 [Quote V2 part 1]

---

KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/Response/Quote/Quote.swift
KarhooSDK/Api/Response/Quote/QuotePrice.swift
KarhooSDK/Api/Response/Quote/QuoteQta.swift
KarhooSDK/Api/Response/Quote/QuoteVehicle.swift
KarhooSDKIntegrationTests/Service/Payment/GetNonceMethod/GetNonceMethodSpec.swift

- Update quote model for quotes v2
- Fix a broken test in GetNonceMethodSpec 

MOB-2858 [Update Quote model]

---

KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/Request/AdyenPaymentMethodsRequestPayload.swift
KarhooSDK/Api/Response/Adyen/AdyenDetail.swift
KarhooSDK/Api/Response/Adyen/AdyenGroup.swift
KarhooSDK/Api/Response/Adyen/AdyenItem.swift
KarhooSDK/Api/Response/Adyen/AdyenPaymentMethod.swift
KarhooSDK/Api/Response/Adyen/AdyenPaymentMethods.swift
KarhooSDK/Api/Response/Adyen/AdyenPaymentMethodsGroup.swift
KarhooSDK/Network/APIEndpoint.swift
KarhooSDK/Service/Payment/AdyenPaymentMethods/AdyenPaymentMethodsInteractor.swift
KarhooSDK/Service/Payment/AdyenPaymentMethods/KarhooAdyenPaymentMethodsInteractor.swift
KarhooSDK/Service/Payment/KarhooPaymentService.swift
KarhooSDK/Service/Payment/PaymentProvider/KarhooPaymentProviderInteractor.swift
KarhooSDK/Service/Payment/PaymentService.swift
KarhooSDKIntegrationTests/JSON/Payment/Adyen/AdyenPaymentMethods.json
KarhooSDKIntegrationTests/Service/Payment/Adyen/AdyenPaymentMethodsSpec.swift
KarhooSDKTests/Mocks/Api/Response/AdyenPaymentMethodMock.swift
KarhooSDKTests/Mocks/Service/Payment/AdyenPaymentMethods/MockAdyenPaymentMethodsInteractor.swift
KarhooSDKTests/TestCases/Service/Payment/AdyenPaymentMethods/KarhooAdyenPaymentMethodsInteractorSpec.swift
KarhooSDKTests/TestCases/Service/Payment/PaymentProvider/KarhooPaymentProviderInteractorSpec.swift

[MOB-2709](https://karhoo.atlassian.net/browse/MOB-2709)
Integrating the new get Adyen payments endpoint with relevant unit tests. Integration tests to follow once the response is available.
N/a

MOB-2709 - Integrate get Adyen payment methods

---

.gitignore
Client/AppDelegate.swift
KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/Response/QuoteList.swift
KarhooSDKTests/Mocks/Api/Response/QuoteListMock.swift
KarhooSDKTests/Mocks/Api/Response/QuoteMock.swift
KarhooSDKTests/TestCases/Networking/KarhooRequestSenderSpec.swift
KarhooSDKTests/TestCases/Service/Payment/KarhooPaymentServiceSpec.swift
KarhooSDKTests/TestCases/Service/Quote/Interactor/KarhooQuoteInteractorSpecV2.swift
KarhooSDKTests/TestCases/Service/Quote/KarhooQuoteServiceSpec.swift

[MOB-2899](https://karhoo.atlassian.net/browse/MOB-2899)
- ignore keys
- fix tests

MOB-2899 [ignore Keys.swift]

---

KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/DataStore/User/UserDataStore.swift
KarhooSDK/Api/Response/Adyen/AdyenPayments/AdyenTransaction.swift
KarhooSDK/Api/Response/PaymentProvider.swift
KarhooSDK/Api/Response/Provider.swift
KarhooSDK/Api/Response/UserInfo.swift
KarhooSDK/Network/APIEndpoint.swift
KarhooSDK/Service/Payment/PaymentProvider/KarhooPaymentProviderInteractor.swift
KarhooSDK/Service/User/LoginInteractor/KarhooLoginInteractor.swift
KarhooSDKIntegrationTests/Service/Auth/AuthLoginMethodSpec.swift
KarhooSDKIntegrationTests/Service/Auth/RevokeMethodSpec.swift
KarhooSDKIntegrationTests/Service/Payment/Adyen/AdyenPaymentsSpec.swift
KarhooSDKTests/Mocks/Api/DataStore/MockUserDataStore.swift
KarhooSDKTests/Mocks/Api/Response/UserInfoMock.swift
KarhooSDKTests/Mocks/Networking/MockRequestSender.swift
KarhooSDKTests/TestCases/Api/DataStore/UserDataStoreSpec.swift
KarhooSDKTests/TestCases/Service/Payment/AdyenPayments/KarhooAdyenPaymentsInteractorSpec.swift
KarhooSDKTests/TestCases/Service/Payment/KarhooPaymentServiceSpec.swift
KarhooSDKTests/TestCases/Service/Payment/PaymentProvider/KarhooPaymentProviderInteractorSpec.swift
KarhooSDKTests/TestCases/Service/User/New Group/KarhooLoginInteractorSpec.swift

[MOB-2910](https://karhoo.atlassian.net/browse/MOB-2910)
- payment provider interactor + login interactor fetching paymet type

MOB-2910 [Payment Provider]

---

KarhooSDK/Network/Header/HeaderProvider.swift
KarhooSDK/Network/Header/KarhooHeaderProvider.swift
KarhooSDK/Network/HttpClient/JsonHttpClient/JsonHttpClient.swift
KarhooSDKTests/TestCases/Networking/Headers/HeaderProviderSpec.swift

headers modifedto enable token exhange

MOB-2922_Headers

---

.gitignore
KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK.xcodeproj/project.xcworkspace/contents.xcworkspacedata
KarhooSDK.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
KarhooSDK/Service/Payment/KarhooPaymentService.swift
KarhooSDKIntegrationTests/Utils/NetworkStubFactory.swift
KarhooSDKTests/TestCases/Service/Payment/KarhooPaymentServiceSpec.swift
Package.resolved
Package.swift
README.md

[MOB-2947](https://karhoo.atlassian.net/browse/MOB-2947)
- Switch from Carthage to Swift Package Manager as Carthage does not cleanly support Xcode 12 until they migrate from Lipo
- Fix the AddPaymentMethods interactor to actually attach the request payload to the request. 

[MOB-2947+Patch] Xcode12 support + Interactor Patch

---

fastlane/Fastfile

slack url updated

---

KarhooSDK/Api/Response/Quote/QuotePrice.swift

Requirement for Adyen integration (requires price as int instead of formatted double) ie 10.00 & 1000

MOB-XXX [Quote price as Int]

---

KarhooSDK/Api/DataStore/User/UserDataStore.swift
KarhooSDK/Service/User/KarhooUserService.swift
KarhooSDKTests/TestCases/Api/DataStore/UserDataStoreSpec.swift

[MOB-2944](https://karhoo.atlassian.net/browse/MOB-2944)
Allows access to payment provider type (braintree / adyen) for guest users.  

MOB-2944 [Persist payment provider for guest users]

---

KarhooSDK/Service/Auth/LoginInteractor/KarhooAuthLoginInteractor.swift
KarhooSDK/Service/User/LoginInteractor/KarhooLoginInteractor.swift
KarhooSDKTests/TestCases/Service/Auth/KarhooAuthLoginInteractorSpec.swift
KarhooSDKTests/TestCases/Service/User/New Group/KarhooLoginInteractorSpec.swift

[MOB-2914](https://karhoo.atlassian.net/browse/MOB-2914)
- When logging in with a token then fetch and persist the payment provider
- When Logging in only attempt to retrieve a payment nonce when the payment provider is braintree 

MOB-2914 [Token Exchange Payment Provider]

---

README.md

update readme with auth methods

---

KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/Response/QuoteVehicle.swift
KarhooSDK/Api/Response/VehicleAvailability.swift
KarhooSDKIntegrationTests/JSON/Quote/QuotesV2.json

Add Vehicle Types and Tags to the Network SDK

MOB-3009: Add Vehicle Types and Tags to the Network SDK

---

KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/Request/VerifyQuotePayload.swift
KarhooSDK/Network/APIEndpoint.swift
KarhooSDK/Service/Quote/Interactor/KarhooVerifyQuoteInteractor.swift
KarhooSDK/Service/Quote/Interactor/VerifyQuoteInteractor.swift
KarhooSDK/Service/Quote/KarhooQuoteService.swift
KarhooSDK/Service/Quote/QuoteService.swift
KarhooSDKIntegrationTests/Service/Quote/VerifyQuoteMethodSpec.swift
KarhooSDKTests/Mocks/Service/Quote/MockVerifyQuoteInteractor.swift
KarhooSDKTests/TestCases/Service/Quote/Interactor/KarhooVerifyQuoteInteractorSpec.swift
KarhooSDKTests/TestCases/Service/Quote/KarhooQuoteServiceSpec.swift

MOB-2979: Quote V2: Verify quote price with DMS before booking
endpoint & tests added

MOB-2979: Quote V2: Verify quote price with DMS before booking

---

KarhooSDK/Api/Request/Adyen/AdyenDropInPayload.swift

[MOB-3058](https://karhoo.atlassian.net/browse/MOB-3058)
object additionalData added to AdyenDroipinPayload.swift

MOB-3058: Add allow3DS2 to Payment request

---

KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/Request/TripBooking.swift
KarhooSDKTests/Mocks/Api/Request/TripBookingMock.swift
KarhooSDKTests/TestCases/Service/Trips/BookingInteractor/KarhooBookingInteractorSpec.swift

[MOB-3066](https://karhoo.atlassian.net/browse/MOB-3066)
Add meta data to pass through trip id to backend for Adyen bookings
N/a

MOB-3066- Add TripBooking meta data

---

KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/Response/FleetInfo.swift
KarhooSDK/Api/Response/FleetRating.swift
KarhooSDK/Api/Response/NetPrice.swift
KarhooSDK/Api/Response/QuotePrice.swift
KarhooSDK/Api/Response/QuoteVehicle.swift
KarhooSDK/Api/Response/VehicleAvailability.swift
KarhooSDKIntegrationTests/JSON/Quote/QuotesV2.json
KarhooSDKTests/TestCases/Service/Trips/BookingInteractor/KarhooBookingInteractorSpec.swift

[MOB-3015](https://karhoo.atlassian.net/browse/MOB-3015)
endpoints edited accordlingly and tests fixed

[MOB-3015]: Update QuoteV2 model

---

KarhooSDK/Api/Response/QuotePrice.swift
KarhooSDKIntegrationTests/JSON/Quote/QuotesV2.json

NO ticket
Fixed some failing tests on develop

[MOB-XXXX] Fix integration tests

---

Cartfile.resolved
KarhooSDK/Api/Request/Adyen/AdyenPaymentsDetailsRequest.swift
KarhooSDK/Api/Response/Adyen/AdyenPayments/AdyenPayments.swift
KarhooSDKIntegrationTests/JSON/Payment/Adyen/AdyenPaymentsWith3DS.json
KarhooSDKIntegrationTests/JSON/Payment/Adyen/AdyenPaymentsWithCard.json
KarhooSDKIntegrationTests/Service/Payment/Adyen/AdyenPaymentsSpec.swift
KarhooSDKTests/TestCases/Service/Payment/AdyenPayments/KarhooAdyenPaymentsInteractorSpec.swift

[MOB-3088](https://karhoo.atlassian.net/browse/MOB-3088)
Update to use trip_id from payments response and in payments-details
N/a

MOB-3088 - Rename Adyen payment transaction_id to trip_id

---

KarhooSDK/Api/Request/TripSearch.swift
KarhooSDK/Api/Response/Passengers.swift

[MOB-3114](https://karhoo.atlassian.net/browse/MOB-3114)
Fixed bug around Upcoming and past rides not retrieved 

[MOB-3114]: Upcoming and past rides not retrieved 

---

KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/Karhoo.swift
KarhooSDK/Api/Response/LoyaltyBalance.swift
KarhooSDK/Network/APIEndpoint.swift
KarhooSDK/Service/Loyalty/KarhooLoyaltyService.swift
KarhooSDK/Service/Loyalty/LoyaltyBalance/KarhooLoyaltyBalanceInteractor.swift
KarhooSDK/Service/Loyalty/LoyaltyBalance/LoyaltyBalanceInteractor.swift
KarhooSDK/Service/Loyalty/LoyaltyService.swift
KarhooSDK/Service/Payment/KarhooPaymentService.swift
KarhooSDKIntegrationTests/JSON/Loyalty/LoyaltyBalanceFalse.json
KarhooSDKIntegrationTests/JSON/Loyalty/LoyaltyBalanceTrue.json
KarhooSDKIntegrationTests/Service/Loyalty/LoyaltyBalanceMethodSpec.swift
KarhooSDKTests/Mocks/Service/Loyalty/MockLoyaltyBalanceInteractor.swift
KarhooSDKTests/TestCases/Api/KarhooSpec.swift
KarhooSDKTests/TestCases/Service/Loyalty/KarhooLoyaltyServiceSpec.swift
KarhooSDKTests/TestCases/Service/Loyalty/LoyaltyBalance/KarhooLoyaltyBalanceInteractorSpec.swift
KarhooSDKTests/TestCases/Service/Trips/CancellationFee/CancellationFeeInteractorSpec.swift
KarhooSDKTests/TestCases/Service/Trips/KarhooTripServiceSpec.swift

[MOB-2985](https://karhoo.atlassian.net/browse/MOB-2985)
Loyalty points user's balance

[MOB-2985]: Loyalty points user's balance

---

KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/Response/LoyaltyConversion.swift
KarhooSDK/Api/Response/LoyaltyRates.swift
KarhooSDK/Network/APIEndpoint.swift
KarhooSDK/Service/Loyalty/KarhooLoyaltyService.swift
KarhooSDK/Service/Loyalty/LoyaltyConversion/KarhooLoyaltyConversionInteractor.swift
KarhooSDK/Service/Loyalty/LoyaltyConversion/LoyaltyConversionInteractor.swift
KarhooSDK/Service/Loyalty/LoyaltyService.swift
KarhooSDKIntegrationTests/JSON/Loyalty/LoyaltyConversion.json
KarhooSDKIntegrationTests/Service/Loyalty/LoyaltyConversionMethodSpec.swift
KarhooSDKTests/Mocks/Api/Response/LoyaltyRatesMock.swift
KarhooSDKTests/Mocks/Service/Loyalty/MockLoyaltyConversionInteractor.swift
KarhooSDKTests/TestCases/Service/Loyalty/KarhooLoyaltyServiceSpec.swift
KarhooSDKTests/TestCases/Service/Loyalty/LoyaltyConversion/KarhooLoyaltyConversionInteractorSpec.swift

[MOB-2986](https://karhoo.atlassian.net/browse/MOB-2986)
Loyalty points conversion rates

[MOB-2986]: Loyalty points conversion rates

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj

[MOB-3086](https://karhoo.atlassian.net/browse/MOB-3086)

[MOB-3086] NSDK Release 1.2.4

---

KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Service/Auth/LoginInteractor/KarhooAuthLoginInteractor.swift
KarhooSDKTests/TestCases/Service/Auth/KarhooAuthLoginInteractorSpec.swift

[MOB-2925](https://karhoo.atlassian.net/browse/MOB-2925)
Retrieve and save payment info for token exchange login
N/a

MOB-2925 - Pre-populate saved Token Exchange payment data

---

KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/Response/QuoteList.swift
KarhooSDK/Api/Response/QuoteStatus.swift
KarhooSDK/Api/Response/Quotes.swift
KarhooSDK/Service/Quote/Interactor/KarhooQuoteInteractor.swift
KarhooSDKTests/Mocks/Api/Response/QuoteListMock.swift
KarhooSDKTests/TestCases/Service/Quote/Interactor/KarhooQuoteInteractorSpec.swift

[MOB-2976](https://karhoo.atlassian.net/browse/MOB-2976)
Tested in the UISDK and Traveller, nothing has broken from these changes.

[MOB-2976] Quote model update for Polling

---

KarhooSDK/Network/APIEndpoint.swift
KarhooSDK/Service/Trip/CancellationFeeInteractor/KarhooCancellationFeeInteractor.swift
KarhooSDKTests/TestCases/Service/Trips/CancellationFee/CancellationFeeInteractorSpec.swift

[MOB-3177](https://karhoo.atlassian.net/browse/MOB-3177)
Add code and tests to use the booking fee follow endpoint for guest user config
N/a

MOB-3177 - Call follow endpoint for guest checkout booking fee retrieval

---

.gitignore

Ignore Package.resolved

---

KarhooSDK/Api/Response/Quote.swift
KarhooSDKIntegrationTests/JSON/Quote/QuotesV2.json
KarhooSDKIntegrationTests/Service/Quote/QuoteSearchMethodSpec.swift

[MOB-3181](https://karhoo.atlassian.net/browse/MOB-3181)

{MOB-3181] Quotes cancellation SLA

---

KarhooSDK/Api/Response/CancellationFeePrice.swift
KarhooSDK/Api/Response/QuotePrice.swift
KarhooSDK/Network/Common/KarhooCodableModel.swift
KarhooSDKIntegrationTests/JSON/Trip/CancellationFee.json
KarhooSDKIntegrationTests/Service/Trip/CancellationFeeMethodSpec.swift

[MOB-3144](https://karhoo.atlassian.net/browse/MOB-3144)
Add decimalValue that adds 2 decimal places to the value
N/a

MOB-3144 - Add decimal formatting to CancellationFeePrice

---

KarhooSDK/Api/Request/Adyen/AdyenPaymentsRequest.swift

[MOB-3175](https://karhoo.atlassian.net/browse/MOB-3175)
Remove suffix url from Adyen payments method

Remove URL suffix

---

KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/Request/Adyen/AdyenDropInPayload.swift
KarhooSDK/Api/Response/Adyen/AdyenPayments/AdyenBrowserInfo.swift

[MOB-3203](https://karhoo.atlassian.net/browse/MOB-3203)
Add BrowserInfo to AdyenDropInPayload to force 3DS on mobile

Add BrowserInfo to Adyen DropIn Payload

---

KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/Response/Fleet.swift
KarhooSDK/Api/Response/Quote.swift
KarhooSDKTests/Mocks/Api/Response/QuoteMock.swift
KarhooSDKTests/TestCases/Service/Quote/Interactor/KarhooVerifyQuoteInteractorSpec.swift
KarhooSDKTests/TestCases/Service/Quote/KarhooQuoteServiceSpec.swift

[MOB-3205](https://karhoo.atlassian.net/browse/MOB-3205)
Add Fleet model to be used in Quote model
Use FleetInfo model to be used in Trip model

Add Fleet model to be used in Quote model

---

KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/Response/ServiceCancellation.swift
KarhooSDK/Api/Response/ServiceCancellationType.swift
KarhooSDKIntegrationTests/JSON/Quote/QuotesV2.json
KarhooSDKIntegrationTests/JSON/Trip/TripInfo.json
KarhooSDKIntegrationTests/Service/Quote/QuoteSearchMethodSpec.swift
KarhooSDKIntegrationTests/Service/Trip/BookTripMethodSpec.swift
KarhooSDKIntegrationTests/Service/Trip/TrackTripMethodSpec.swift

[MOB-3179](https://karhoo.atlassian.net/browse/MOB-3179)

Make service cancellation type an enum

---

Gemfile.lock
KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj

[MOB-3216](https://karhoo.atlassian.net/browse/MOB-3216)

[MOB-3216] Release 1.4.0

---

KarhooSDK/Api/Response/TripInfo.swift

[MOB-3383](https://karhoo.atlassian.net/browse/MOB-3383)
Use date data type for dateBooked

Use date data type for dateBooked

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj

[MOB-3387](https://karhoo.atlassian.net/browse/MOB-3387)

MOB-3387 Release 1.5.0

---

KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/DataStore/User/Credentials.swift
KarhooSDK/Api/Response/AuthToken.swift
KarhooSDK/Service/Auth/AuthService.swift
KarhooSDK/Service/Auth/KarhooAuthService.swift
KarhooSDK/Service/Auth/LoginInteractor/AuthLoginWithCredentialsInteractor.swift
KarhooSDK/Service/Auth/LoginInteractor/AuthLoginWithTokenInteractor.swift
KarhooSDK/Service/Auth/LoginInteractor/KarhooAuthLoginWithCredentialsInteractor.swift
KarhooSDK/Service/Auth/LoginInteractor/KarhooAuthLoginWithTokenInteractor.swift
KarhooSDKTests/TestCases/Service/Auth/KarhooAuthLoginInteractorSpec.swift
KarhooSDKTests/TestCases/Service/Auth/KarhooAuthLoginWithCredentialsSpec.swift

[MOB-3438](https://karhoo.atlassian.net/browse/MOB-3438)

[MOB-3438] login with credentials

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/Response/AuthToken.swift
KarhooSDK/Service/Auth/AuthService.swift
KarhooSDK/Service/Auth/KarhooAuthService.swift
KarhooSDK/Service/Auth/LoginInteractor/AuthLoginWithCredentialsInteractor.swift
KarhooSDK/Service/Auth/LoginInteractor/AuthLoginWithTokenInteractor.swift
KarhooSDK/Service/Auth/LoginInteractor/KarhooAuthLoginWithCredentialsInteractor.swift
KarhooSDK/Service/Auth/LoginInteractor/KarhooAuthLoginWithTokenInteractor.swift
KarhooSDKTests/TestCases/Service/Auth/KarhooAuthLoginWithCredentialsSpec.swift

[MOB-3450](https://karhoo.atlassian.net/browse/MOB-3450)

Post release 1 5 1

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj

[MOB-3450](https://karhoo.atlassian.net/browse/MOB-3450)

Release 1.5.1

---

KarhooSDK/Api/Response/AuthToken.swift

[MOB-3445](https://karhoo.atlassian.net/browse/MOB-3445)
Changed the access level from internal to public for the AuthToken init

change AuthToken init access level from internal to public

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/Response/AuthToken.swift
README.md

[MOB-3488](https://karhoo.atlassian.net/browse/MOB-3488)

MOB-3488 Post release 1.5.2 (master)

---

KarhooSDK/Api/Response/Fleet.swift

[MOB-3405](https://karhoo.atlassian.net/browse/MOB-3405)

MOB-3405 fix coding key for fleet capabilties

---

KarhooSDK/Api/Request/TripBooking.swift

[MOB-3632](https://karhoo.atlassian.net/browse/MOB-3632)

[MOB-3632] Add loyalty nonce to booking api

---

KarhooSDK/Api/Response/PaymentProvider.swift
KarhooSDKIntegrationTests/JSON/Payment/PaymentProvider/PaymentProvider.json

[MOB-xxxx] Modify LoyaltyProgramme to be an Object vs an Array

---

.circleci/config.yml
KarhooSDKIntegrationTests/Service/Loyalty/LoyaltyBalanceMethodSpec.swift

Mob xxxx circleci fix

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
README.md

[MOB-3749](https://karhoo.atlassian.net/browse/MOB-3749)

MOB-3749_release_1_5_4 bump version

---

KarhooSDK/Api/Request/Adyen/AdyenPaymentMethodsRequest.swift

[MOB-3819](https://karhoo.atlassian.net/browse/MOB-3819)

MOB-3819 add shopper locale to adyen payment request

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
README.md

[MOB-3893](https://karhoo.atlassian.net/browse/MOB-3893)

MOB-3893 bump version to 1.5.5 [DEVELOP]

---

.circleci/config.yml
KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/Request/Adyen/AdyenPaymentMethodsRequest.swift
KarhooSDK/Service/Analytics/AnalyticsConstants.swift
README.md

[MOB-3893](https://karhoo.atlassian.net/browse/MOB-3893)

Mob 3893 post release 1 5 5 [MASTER]

---

KarhooSDK/Service/Quote/CategoryQuoteMapper.swift
KarhooSDK/Service/Quote/Interactor/KarhooQuoteInteractor.swift
KarhooSDKIntegrationTests/JSON/Quote/QuotesV2.json
KarhooSDKIntegrationTests/Service/Quote/QuoteSearchMethodSpec.swift
KarhooSDKTests/Mocks/Api/Response/QuoteMock.swift

[MOB-3942](https://karhoo.atlassian.net/browse/MOB-3942)
Filters for quote list updated

change vehicle class to vehicle type in quote categories

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/Response/PaymentProvider.swift
KarhooSDK/Network/APIEndpoint.swift
KarhooSDK/Service/Payment/AdyenAPIVersionProvider/AdyenAPIVersionProvider.swift
KarhooSDK/Service/Payment/AdyenAPIVersionProvider/KarhooAdyenAPIVersionProvider.swift
KarhooSDK/Service/Payment/AdyenPaymentMethods/KarhooAdyenPaymentMethodsInteractor.swift
KarhooSDK/Service/Payment/AdyenPayments/KarhooAdyenPaymentsInteractor.swift
KarhooSDK/Service/Payment/AdyenPaymentsDetails/KarhooAdyenPaymentsDetailsInteractor.swift
KarhooSDK/Service/Payment/KarhooPaymentService.swift
KarhooSDKTests/TestCases/Service/Payment/AdyenPaymentMethods/KarhooAdyenPaymentMethodsInteractorSpec.swift
KarhooSDKTests/TestCases/Service/Payment/AdyenPayments/KarhooAdyenPaymentsInteractorSpec.swift
KarhooSDKTests/TestCases/Service/Payment/AdyenPaymentsDetails/KarhooPaymentsDetailsInteractorSpec.swift
README.md

[MOB-4024](https://karhoo.atlassian.net/browse/MOB-4024)

Mob 4024 post release 1.6 [DEVELOP]

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/Response/PaymentProvider.swift
KarhooSDK/Api/Response/Provider.swift
KarhooSDK/Service/Payment/AdyenAPIVersionProvider/KarhooAdyenAPIVersionProvider.swift
README.md

…related calls (#142)
* Add `version` parameter to PaymentProvider model
* Payment API Version added to payments interactors and endpints
* force v68 api version for debug
* Payment version added to path if differs from v51
* version path component fix
* version string calculation improved
* Test v68 version
* update tests
* version bump 1.5.5 => 1.5.6
* Change version number
* MOB-4021 cherry pick
* SPM updated
* fetching payment provider api version fixed
* Unit tests update
* SPM update reverted due to CI issue
* remove `version` parameter form PaymentProvider model …

MOB-4020 post release 1.6.1 [master]

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
KarhooSDK/Api/Response/Provider.swift
KarhooSDK/Service/Payment/AdyenAPIVersionProvider/KarhooAdyenAPIVersionProvider.swift
README.md

MOB-4020 post release 1.6.1 [develop]

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
README.md

[MOB-4140](https://karhoo.atlassian.net/browse/MOB-4140)

bump version to 1.6.2 [DEVELOP]

---

Gemfile.lock
KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
KarhooSDK/Api/Response/PaymentProvider.swift
KarhooSDK/Service/Auth/LoginInteractor/KarhooAuthLoginWithCredentialsInteractor.swift
KarhooSDK/Service/Auth/LoginInteractor/KarhooAuthLoginWithTokenInteractor.swift
KarhooSDK/Service/Quote/CategoryQuoteMapper.swift
KarhooSDK/Service/Quote/Interactor/KarhooQuoteInteractor.swift
KarhooSDK/Service/User/LoginInteractor/KarhooLoginInteractor.swift
KarhooSDKIntegrationTests/JSON/Quote/QuotesV2.json
KarhooSDKIntegrationTests/Service/Config/UIConfigMethodSpec.swift
KarhooSDKIntegrationTests/Service/Quote/QuoteSearchMethodSpec.swift
KarhooSDKTests/Mocks/Api/Response/QuoteMock.swift
KarhooSDKTests/TestCases/Service/Auth/KarhooAuthLoginInteractorSpec.swift
KarhooSDKTests/TestCases/Service/Auth/KarhooAuthLoginWithCredentialsSpec.swift
KarhooSDKTests/TestCases/Service/User/New Group/KarhooLoginInteractorSpec.swift
README.md

[MOB-4140](https://karhoo.atlassian.net/browse/MOB-4140)

Mob 4140 post release 1 6 2 [MASTER]

---

.gitignore
KarhooSDK.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
KarhooSDK/Api/Util/Result.swift
KarhooSDK/Network/Common/RequestSender/KarhooRequestSender.swift
KarhooSDK/Network/HttpClient/JsonHttpClient/JsonHttpClient.swift
KarhooSDK/Service/Analytics/AnalyticsConstants.swift
KarhooSDK/Service/Auth/LoginInteractor/KarhooAuthLoginWithCredentialsInteractor.swift
KarhooSDK/Service/Auth/LoginInteractor/KarhooAuthLoginWithTokenInteractor.swift
KarhooSDK/Service/Payment/AdyenPaymentMethods/KarhooAdyenPaymentMethodsInteractor.swift
KarhooSDK/Service/Payment/AdyenPaymentsDetails/KarhooAdyenPaymentsDetailsInteractor.swift
KarhooSDK/Service/Trip/TripUpdate/KarhooTripUpdateInteractor.swift
KarhooSDK/Service/User/UpdateUserDetailsInteractor/KarhooUpdateUserDetailsInteractor.swift

[MOB-4166](https://karhoo.atlassian.net/browse/MOB-4166)
APPROACH A
This pr presents network sdk will change if we decide to extend current Result structure and create tuples in success/failure case, and add correlationId as a second component.
related [UI SDK pull request](https://github.com/karhoo/karhoo-ios-ui-sdk/pull/350)

Feature/mob 4160 extract correlation - APPROACH A

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Service/User/KarhooPaymentProviderUpdateHandler.swift
README.md

[MOB-4219](https://karhoo.atlassian.net/browse/MOB-4219)

MOB-4219 release 1.6.3 (DEVELOP)

---

KarhooSDK/Api/DataStore/User/UserDataStore.swift

fix read/store operations in UserDataStore

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Api/DataStore/User/Credentials.swift
KarhooSDKTests/Mocks/ObjectTestFactory.swift
Package.swift
README.md

[MOB-4371](https://karhoo.atlassian.net/browse/MOB-4371)

MOB-4371 release 1.7.0 [DEVELOP]

---

KarhooSDK/Network/Common/Error/KarhooError.swift
KarhooSDK/Network/Common/Error/KarhooErrorType.swift
KarhooSDK/Network/Common/Error/KarhooSDKError.swift

[MOB-3663](https://karhoo.atlassian.net/browse/MOB-3663)

3663 - add new error codes to sdk

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
README.md

[MOB-4501](https://karhoo.atlassian.net/browse/MOB-4501)

MOB 4501 bump version [DEVELOP]

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK/Network/Common/Error/KarhooError.swift
KarhooSDK/Network/Common/Error/KarhooErrorType.swift
KarhooSDK/Network/Common/Error/KarhooSDKError.swift
KarhooSDK/Service/Analytics/AnalyticsConstants.swift
README.md

[MOB-4501](https://karhoo.atlassian.net/browse/MOB-4501)

Mob 4501 post release 1 7 1 [MASTER]

---

KarhooSDK/Api/Request/Adyen/AdyenPaymentsRequest.swift

[MOB-4528](https://karhoo.atlassian.net/browse/MOB-4528)

MOB-4528 new field added to adyen payments request

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
README.md

[MOB-4590](https://karhoo.atlassian.net/browse/MOB-XXXX)
[MOB-4590]: https://karhoo.atlassian.net/browse/MOB-4590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB-4590 release 1.7.2

---

KarhooSDK/Network/APIEndpoint.swift
KarhooSDK/Service/Quote/Interactor/KarhooQuoteCoverageInteractor.swift
KarhooSDKTests/TestCases/Service/Quote/Interactor/KarhooQuoteCoverageInteractorSpec.swift

[MOB-4675](https://karhoo.atlassian.net/browse/MOB-4675)
[MOB-4675]: https://karhoo.atlassian.net/browse/MOB-4675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB-4675 Required updated to coverage check call

---

KarhooSDK.xcodeproj/project.pbxproj

[MOB-0000](https://karhoo.atlassian.net/browse/MOB-0000)

MOB-0000 config fix

---

KarhooSDK/Api/Response/QuoteVehicle.swift

[MOB-4100](https://karhoo.atlassian.net/browse/MOB-4100)
[MOB-4100]: https://karhoo.atlassian.net/browse/MOB-4100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB-4100 remove default passenger and luggage values

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
README.md

[MOB-4764](https://karhoo.atlassian.net/browse/MOB-4764)
[MOB-4764]: https://karhoo.atlassian.net/browse/MOB-4764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB-4764 Release 1.8.0 preparation

---

CODEOWNERS
CODEOWNERS.bak

https://karhoo.atlassian.net/browse/INF-2818
Changing team name in CODEOWNERS.
- [ x] Tech Debt
- [ x] Lint and unit tests pass locally (if appropriate)
- [ x] Added tests that prove the fix is effective or that feature works (if appropriate)
- [ x] Documentation (if appropriate)

INF-2818 change codeowners

---

KarhooSDK.xcodeproj/project.pbxproj

[MOB-4880](https://karhoo.atlassian.net/browse/MOB-4880)
[MOB-4880]: https://karhoo.atlassian.net/browse/MOB-4880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB-4880 fix xcode 14.3.1 test target errors

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
README.md

[MOB-4885](https://karhoo.atlassian.net/browse/MOB-4885)
[MOB-4885]: https://karhoo.atlassian.net/browse/MOB-4885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB-4885 release 1.8.1

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
README.md

[MOB-4893](https://karhoo.atlassian.net/browse/MOB-4893)
[MOB-4893]: https://karhoo.atlassian.net/browse/MOB-4893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB-4893 release 1.8.2

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
KarhooSDK.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
KarhooSDK/Api/DataStore/KeychainSecretStore.swift
KarhooSDK/Api/Util/DeviceIdentifierProvider.swift
KarhooSDK/Utils/Keychain/KeychainSwift.swift
KarhooSDK/Utils/Keychain/KeychainSwiftAccessOptions.swift
KarhooSDK/Utils/Keychain/TegKeychainConstants.swift
KarhooSDK/Utils/Keychain/concatenate_swift_files.sh
KarhooSDK/Utils/Reachability/Reachability.swift
KarhooSDK/Utils/Reachability/ReachabilityWrapper.swift
KarhooSDKTests/TestCases/Networking/ReachabilityWrapperSpec.swift
Package.swift

[MOB-4887](https://karhoo.atlassian.net/browse/MOB-4887)
[MOB-4887]: https://karhoo.atlassian.net/browse/MOB-4887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB-4887 remove dependencies

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
README.md

[MOB-4887](https://karhoo.atlassian.net/browse/MOB-4887)
[MOB-4887]: https://karhoo.atlassian.net/browse/MOB-4887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB-4887 release 1.8.3

---

KarhooSDK/Network/APIEndpoint.swift
KarhooSDK/Service/Quote/Interactor/KarhooQuoteInteractor.swift
KarhooSDK/Service/Quote/Interactor/QuoteInteractor.swift
KarhooSDK/Service/Quote/KarhooQuoteService.swift
KarhooSDK/Service/Quote/QuoteService.swift
KarhooSDKTests/Mocks/Service/Quote/MockQuoteInteractor.swift
KarhooSDKTests/TestCases/Networking/Headers/HeaderProviderSpec.swift
KarhooSDKTests/TestCases/Service/Quote/Interactor/KarhooQuoteInteractorSpec.swift

[MOB-3694](https://karhoo.atlassian.net/browse/MOB-3694)
[MOB-3694]: https://karhoo.atlassian.net/browse/MOB-3694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB-3694 add locale to quote list request

---

KarhooSDK/Service/Quote/QuoteService.swift

[MOB-3694](https://karhoo.atlassian.net/browse/MOB-3694)
[MOB-3694]: https://karhoo.atlassian.net/browse/MOB-3694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB-3694 small amendament

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
README.md

[MOB-4909](https://karhoo.atlassian.net/browse/MOB-4909)
[MOB-4909]: https://karhoo.atlassian.net/browse/MOB-4909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB-4909 bump version to 1.8.4

---

KarhooSDK.podspec
KarhooSDK.xcodeproj/project.pbxproj
README.md

[MOB-4937](https://karhoo.atlassian.net/browse/MOB-4937)
[MOB-4937]: https://karhoo.atlassian.net/browse/MOB-4937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB-4937 bump version to 1.8.5
